### ISSUE TITLE
Need a version of the sample that uses loginRedirect

### ISSUE THREAD

**Issue by hhubik** [Azure-Samples/active-directory-b2c-javascript-angular2.4-spa#10]
Thank you for providing this example.  I would really appreciate if you could also add an example that uses redirect rather than popup for the authentication. Alternatively, please provide some guidance on what needs to be changed in the [MSAL Service code](https://github.com/Azure-Samples/active-directory-b2c-javascript-angular2.4-spa/blob/master/src/app/services/msal.service.ts) to make it use redirect instead of popup.

**Comment by Gimly** [comment]
@hhubik Did you manage to get the login redirect to work correctly? I'm completely stuck, I've tried to add the calls to this in the callback of the `UserAgentApplication` constructor, but it doesn't work. The calls to `acquireTokenSilent` always fail, so are the calls to `acquireTokenPopup`.

```TypeScript
this.clientApplication.acquireTokenSilent(this.tenantConfig.b2cScopes)
            .then(token => {
                console.log("Got silent access token: ", token);
                accessToken = token;
            }).catch(error => {
                console.log("Could not silently retrieve token from storage.", error);
                this.clientApplication.acquireTokenPopup(this.tenantConfig.b2cScopes)
                    .then(token => {
                        console.log("Got popup access token: ", token);
                        accessToken = token;
                    }).catch(error => {
                        console.log("Could not retrieve token from popup.", error);
                        this.clientApplication.acquireTokenRedirect(this.tenantConfig.b2cScopes);
                    });
            });
```

**Comment by hhubik** [comment]
@Gimly I could not get it to work.  According to [this](https://stackoverflow.com/questions/46493650/can-i-use-my-own-ui-to-authenticate-users-with-azure-ad-b2c), it seems like using your own UI is not possible at the moment. I switched to [Auth0](https://auth0.com/) for now where I had no trouble doing that.

**Comment by jmprieur** [comment]
Closing this issue as this sample is being archived (newer sample available)
