### ISSUE TITLE
Need better samples for ASP.NET Core 2 and Angular

### ISSUE THREAD

**Issue by jwettstrom** [Azure-Samples/active-directory-b2c-javascript-angular2.4-spa#11]
There are no Azure AD B2C samples I could find for Angular single page (through ASP.NET Core 2 VS 2017 Angular template for new project) and ASP.NET Core 2 Web API. I would suggest someone create these. Too many old ASP.NET Core 1 samples out there that do not work with ASP.NET Core 2. The interaction with Angular (ASP.NET Core 2 backend) and Web API seems none existent for B2C scenario.

**Comment by jmprieur** [comment]
Closing this issue as this sample is being archived (newer sample available)
