### ISSUE TITLE
Cannot find primary outlet to load 'HomeComponent'

### ISSUE THREAD

**Issue by pvrao80** [Azure-Samples/active-directory-b2c-javascript-angular2.4-spa#12]
Hi,
I am getting the error Cannot find primary outlet to load 'HomeComponent' and unable to see the ToDo app which i believe is supposed to get to UNHIDDEN state on successful login.

I am able to login using my azure app details, but not able to get the Todo app . Can you help in resolving the above error

**Comment by imchaitanya9** [comment]
Check your sessionStorage.

**Comment by pvrao80** [comment]
I am not sure where Sessionstorage or localstorage is - can you provide more guidance..

**Comment by quintes** [comment]
this appears to remain in the same, and is not related to storage but to router outlet. Why not update the samples?

**Comment by jmprieur** [comment]
Closing this issue as this sample is being archived (newer sample available)
