### ISSUE TITLE
Msal logout issue 

### ISSUE THREAD

**Issue by chinmayembedded** [Azure-Samples/active-directory-b2c-javascript-angular2.4-spa#16]
Whenever I do logout the ideal behaviour should be like it redirects to the redirect url specified. But sometimes it doesnt redirect to the redirect url instead it routes to some another route and keeps loading the page recursively.

Can you please help me with this issue?

**Comment by imchaitanya9** [comment]
The behaviour is like when you logout from anyother URL except root e.g, `domain.com/child-page`
then you'll get this issue.

So, when you create your UserAgentApplication Object, you need to pass `postLogoutRedirectUri: window.location.origin + '/'` in options object.

```
const userAgentApplication = new UserAgentApplication(
this.tenantConfig.clientId,
this.AUTHORITY,
this.authCallback,
      {
        cacheLocation: 'sessionStorage',
        redirectUri: window.location.origin + '/',
        postLogoutRedirectUri: window.location.origin + '/'
      }
    );
```

**Comment by chinmayembedded** [comment]
I have implemented the mentioned code. For the scenarios that I have tested its working fine. Thank you!
