### ISSUE TITLE
MSAL logout process

### ISSUE THREAD

**Issue by chinmayembedded** [Azure-Samples/active-directory-b2c-javascript-angular2.4-spa#19]
When i do logout, i get one intermediate screen as shown in image and then the login page. I dont know why and how i get that screen. Is that screen to be created in azure portal or any parameters to add in the code that will bypass this screen?

![logout](https://user-images.githubusercontent.com/18334906/40642518-f27d540e-633a-11e8-953b-1f76788b5029.png)

**Comment by jmprieur** [comment]
Closing this issue as this sample is being archived (newer sample available)
