### ISSUE TITLE
Question - Support for Microsoft Account?

### ISSUE THREAD

**Issue by hkusulja** [Azure-Samples/active-directory-b2c-javascript-angular2.4-spa#2]
Does this also supports for MSAL and private Microsoft Accounts? or only Azure AD B2C MSAL apps?

Thank you

**Comment by parakhj** [comment]
MSAL js supports Azure AD as well, but this sample is only meant for Azure AD B2C apps

**Comment by hkusulja** [comment]
MSAL currently does not support normal/tenant Azure AD (nor users, nor apps), it only supports Azure AD B2C. Please confirm.
So for company internal applications, MSAL should not be used (because of Azure AD B2C), and normal ADAL with normal Azure AD should be used for internal apps.
The problem is if you have to create application which includes internal company users and external users (like facebook, Microsoft Account, and from other normal Azure AD tenants) ....

**Comment by parakhj** [comment]
MSAL also supports Azure AD tenants. 

If you would like to create an app that has internal company users and external users, you should use Azure AD B2C and add the option to allow users to sign in using social identity providers as well as your company's Azure AD tenant (https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-setup-aad-custom). Azure AD Idps are currently only possible using custom policies, but the feature is coming soon to built in policies.

**Comment by hkusulja** [comment]
As far as I understand, this currently not official answer nor officially supported nor in any preview, but it should work like that.
We do not have any clue when it will be available officially, (GA or preview), or how it will work in...

**Comment by gsacavdm** [comment]
@hkusulja , read [this blog post](https://azure.microsoft.com/en-us/blog/start-writing-applications-today-with-the-new-microsoft-authentication-sdks/) the official statements on ADAL and MSAL, both with regards to regular Azure AD and Azure AD B2C.

Quoting from it:

> MSAL is an SDK that makes it easy for you to obtain the tokens required to access web API protected by Microsoft identities, that is to say by **the v2 protocol endpoint of Azure AD (work and school accounts or Personal Microsoft Accounts), Azure AD B2C**, or the new ASP.NET Core Identity.
>
> ...
>
> You might be wondering, should I be using MSAL or the Active Directory Authentication Library (ADAL)? The answer is straightforward: if you are building an application that needs to support both Azure AD work and school accounts and Microsoft personal accounts (with the v2 protocol endpoint of Azure AD), or building an app that uses Azure AD B2C, then use MSAL. If you’re building an application that needs to support just Azure AD work and school accounts, then use ADAL. In the future, we’ll recommend all apps use MSAL, but not yet.

**Comment by hkusulja** [comment]
I need both cases (once is Azure AD B2C with MSAL supporting AAD and MS Accounts and other accounts from B2C like Facebook).
And second case (only internal application inside AAD)

What are the limits of MSAL comparing to ADAL, for internal application for instance and regular Azure AD ? and why not have one solution?

**Comment by gsacavdm** [comment]
Not sure I understand your first point...
You can use MSAL with Azure AD B2C and support local accounts, social accounts (like Facebook and Microsoft Accounts), and now with [custom policies](https://docs.microsoft.com/azure/active-directory-b2c/active-directory-b2c-overview-custom), also [support Azure AD accounts](https://docs.microsoft.com/azure/active-directory-b2c/active-directory-b2c-setup-aad-custom).

If you only need support for Microsoft Accounts and Azure AD accounts, use MSAL with the Azure AD v2 endpoint (no B2C).

If you only need support for Azure AD accounts, use ADA with Azure AD v1 endpoint.

As for why do the limits exist, from the blog post:

> In the future, we’ll recommend all apps use MSAL, but not yet.

The goal is to only have MSAL as the answer, but it'll take some time to get MSAL to parity.
