### ISSUE TITLE
MSAL SPA - Angular JS 1.7 issue

### ISSUE THREAD

**Issue by swapnild2111** [Azure-Samples/active-directory-b2c-javascript-angular2.4-spa#23]
Hello,
I am trying MSLA spa with Angular js 1.7 and unable to refresh token. However with your example, it works perfect. The only difference is angular js version - you have 2.4 and I have 1.7.

Do you know if there is issue with 1.7? or any workaround in 1.7?

**Comment by jmprieur** [comment]
Closing this issue as this sample is being archived (newer sample available)
