### ISSUE TITLE
Typings for MSAL and ADAL

### ISSUE THREAD

**Issue by jabil-rg02** [Azure-Samples/active-directory-b2c-javascript-angular2.4-spa#25]
This is more a feature request than an issue.  Can you you guys provide typings (typescript definitions) for ADAL or MSAL?  The standard for including typescript definitions in a project is this:

npm install --save @types/adal 
-- or 
npm install --save @types/msal

neither of those work as of this issue

**Comment by jabil-rg02** [comment]
The nice thing about definition files is you don't need to worry about what kind of module system users are working with ... Is it commonjs, is it node? It doesn't matter it's just a definition file.  I can't get the full libraries compiling with imported properly with MSAL or ADAL even though I have the source.  Everyone else has a nice definition file that works right alongside their javascript compiled source

**Comment by jmprieur** [comment]
Archiving this sample (newer sample available)
