### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by iqans** [Azure-Samples/active-directory-b2c-javascript-angular2.4-spa#6]
1. needs to specify `<router-outlet>` in home.html
2. after login doesn't get accesstokens. see exception below:

EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'clientApplication' of undefined
TypeError: Cannot read property 'clientApplication' of undefined
    at eval (https://localhost:3002/app/services/msal.service.js:31:17)

**Comment by parakhj** [comment]
This sample currently don't support calling an API using access tokens. It currently only shows you how you can obtain an id/access token. We are working to update it.

**Comment by cheoalfredo** [comment]
i keep getting "src/app/services/msal.service.ts(3,23): error TS2307: Cannot find module 'msal'." and i have run "npm install msal"

**Comment by simonneedham** [comment]
This sample is currently broken and is going to need a lot of love to get it up and running again, TBH, starting again with `ng new` would be best.

At the moment a simple hello world example of using B2C + MSAL + Angular can be found here: https://github.com/Gimly/simpleAngularAzureB2C.

**Comment by jmprieur** [comment]
Closing this issue as this sample is being archived (newer sample available)
